"""Hermes CIO state — deterministic aggregation of the dashboard into a single
"CIO View" payload (Risk Budget + season + liquidity/cycle/confidence + summary).

This is everything the future GPT 5.5 Hermes agent will reason about, except
free-form Q&A. By keeping the state purely deterministic (no LLM), the frontend
card stays cheap and predictable, and tests can pin its outputs.

See build-28th-may.md §2 (CIO card fields), §11 (weekly message), §12-13 (MIT,
SLR overlays).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime
from typing import Any
from zoneinfo import ZoneInfo

from app.services.risk_budget import RiskBudget, compute as compute_rb
from app.services import mit_overlay as _mit_overlay
from app.services import slr_note as _slr_note


# Per spec §12: MIT is a qualitative overlay, not a scoring input.
# Sourced from `mit_overlay.current()` which reads a Perplexity-fetched cache.
# This constant is the last-resort fallback when no cache exists.
DEFAULT_MIT_OVERLAY = _mit_overlay.DEFAULT_TEXT

# Per spec §13: SLR/eSLR is a small plumbing note, not a core liquidity factor.
# Computed by `slr_note.current_note()` based on the eSLR effectiveness date.
DEFAULT_SLR_NOTE = _slr_note.current_note()


@dataclass
class HermesState:
    stance: str
    risk_budget: int
    deploy_pct: int
    cash_pct: int
    macro_season: str
    liquidity_state: str
    cycle_state: str
    confidence: str
    last_updated: str
    summary: str
    mit_overlay: str = DEFAULT_MIT_OVERLAY
    slr_note: str = DEFAULT_SLR_NOTE
    risk_budget_detail: dict[str, Any] = field(default_factory=dict)
    season_detail: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        return {
            "stance": self.stance,
            "risk_budget": self.risk_budget,
            "deploy_pct": self.deploy_pct,
            "cash_pct": self.cash_pct,
            "macro_season": self.macro_season,
            "liquidity_state": self.liquidity_state,
            "cycle_state": self.cycle_state,
            "confidence": self.confidence,
            "last_updated": self.last_updated,
            "summary": self.summary,
            "mit_overlay": self.mit_overlay,
            "slr_note": self.slr_note,
            "risk_budget_detail": self.risk_budget_detail,
            "season_detail": self.season_detail,
        }


# ── Deterministic summary template ──────────────────────────────────────────
# Until the GPT 5.5 agent lands, summary text is generated by rule. The spec's
# example (§2) for Cautious Risk-On is used as the template:
#
#   "Maintain core exposure, but do not press maximum risk until liquidity
#    confirms. Deploy new capital in tranches. No leverage."
#
# We provide one canonical paragraph per stance and append a one-line season
# rider when the season agrees or disagrees with the stance.

_STANCE_SUMMARY = {
    "Fortress Mode": (
        "Maximum defence. Hold cash and high-quality short duration. Wait for liquidity to turn before re-engaging. "
        "Do not chase rallies on this print."
    ),
    "Defensive": (
        "Defensive posture. Keep a meaningful cash buffer and lean on quality. "
        "Add risk only on confirmed signals — do not pre-empt a turn."
    ),
    "Cautious Risk-On": (
        "Maintain core exposure, but do not press maximum risk until liquidity confirms. "
        "Deploy new capital in tranches. No leverage."
    ),
    "Constructive Risk-On": (
        "Constructive. Run core risk and add on dips. Trim only on macro deterioration; "
        "do not let cash drift above the band's reserve."
    ),
    "Full Risk-On": (
        "Press risk. The macro throttle is green: deploy fresh capital quickly and stay long. "
        "Leverage discretionary; cash reserve is the band minimum."
    ),
}


def _season_rider(stance: str, season: str) -> str:
    """One-line addendum that tells the user whether the season agrees with the stance."""
    s = (season or "").lower()
    bullish_seasons = {"spring", "summer"}
    bearish_seasons = {"autumn", "winter"}
    is_risk_on_stance = stance in {"Cautious Risk-On", "Constructive Risk-On", "Full Risk-On"}
    if s in bullish_seasons and is_risk_on_stance:
        return f"Season ({season}) aligns with the stance — let positions work."
    if s in bearish_seasons and not is_risk_on_stance:
        return f"Season ({season}) confirms defensive bias — do not fight the regime."
    if s in bullish_seasons and not is_risk_on_stance:
        return f"Season ({season}) is supportive but Risk Budget is not — wait for the score to catch up."
    if s in bearish_seasons and is_risk_on_stance:
        return f"Season ({season}) disagrees with the stance — size more conservatively than the band suggests."
    return ""


def build_summary(rb: RiskBudget, season: str, *, llm_enriched: bool = True) -> str:
    """Build the CIO View summary. If Hermes is locally available and
    `llm_enriched=True`, try the LLM first and fall back to the deterministic
    template on any failure."""
    if llm_enriched:
        try:
            from app.services import hermes_llm as _hermes_llm
            payload = {
                "stance": rb.stance,
                "risk_budget": rb.score,
                "deploy_pct": rb.deploy_pct,
                "cash_pct": rb.cash_pct,
                "macro_season": season,
                "liquidity_state": None,
                "cycle_state": None,
                "confidence": rb.confidence,
                "risk_budget_detail": rb.to_dict(),
            }
            prose = _hermes_llm.ask(_hermes_llm.summary_prompt(payload))
            if prose:
                return prose
        except Exception:
            pass
    base = _STANCE_SUMMARY.get(rb.stance, _STANCE_SUMMARY["Cautious Risk-On"])
    rider = _season_rider(rb.stance, season)
    return f"{base} {rider}".strip()


def build(
    scenario: dict[str, float | None],
    season: str,
    liquidity_state: str,
    cycle_state: str,
    timezone: str = "Europe/London",
    season_detail: dict[str, Any] | None = None,
    mit_overlay: str | None = None,
    slr_note: str | None = None,
    runtime_dir: Any = None,
) -> HermesState:
    """Assemble the CIO View from current macro state.

    Inputs:
      scenario        — 7-factor dict from `auto_fill_scenario(snapshot, backtest)`
      season          — phase label from `PhaseService.get().label` ("Spring" / ...)
      liquidity_state — `snapshot.dashboards.liquidity.status` (e.g. "EXPANDING")
      cycle_state     — `snapshot.dashboards.business-cycle.status` (e.g. "EXPANSION")
    """
    rb = compute_rb(scenario)
    now = datetime.now(ZoneInfo(timezone)).isoformat(timespec="minutes")
    # Dynamic overlays — fall back to the static text if the cache is missing.
    if mit_overlay is None and runtime_dir is not None:
        mit_overlay = _mit_overlay.current(runtime_dir)
    if slr_note is None:
        slr_note = _slr_note.current_note()
    return HermesState(
        stance=rb.stance,
        risk_budget=rb.score,
        deploy_pct=rb.deploy_pct,
        cash_pct=rb.cash_pct,
        macro_season=season or "Unknown",
        liquidity_state=liquidity_state or "Unknown",
        cycle_state=cycle_state or "Unknown",
        confidence=rb.confidence,
        last_updated=now,
        summary=build_summary(rb, season),
        mit_overlay=mit_overlay or DEFAULT_MIT_OVERLAY,
        slr_note=slr_note or DEFAULT_SLR_NOTE,
        risk_budget_detail=rb.to_dict(),
        season_detail=season_detail or {},
    )
